# Aggregate e Grouping

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('primary-results.csv')

In [7]:
df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078

In [8]:
df.groupby('candidate').aggregate({'votes':[min,np.mean,max]})

                votes
                  min         mean     max
candidate
 No Preference      0    23.225071     580
 Uncommitted        0     0.434343      16
Ben Carson          0   338.258238    9945
Bernie Sanders      0  2844.019501  434656
Carly Fiorina       0   139.366972    3612
Chris Christie      1   223.422018    7144
Donald Trump        0  3709.576408  179130
Hillary Clinton     0  3731.855410  590502
Jeb Bush            2   609.103226    9575
John Kasich         0  1160.052705  101217
Marco Rubio         0  1299.834051  111898
Martin O'Malley     0     7.595960     152
Mike Huckabee       2    33.787879     565
Rand Paul           2    85.646465    1633
Rick Santorum       0    18.000000     234
Ted Cruz            0  2120.191299  147721

In [10]:
df.loc[df['votes']==590502]

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
1386,California,CA,Los Angeles,6037.0,Democrat,Hillary Clinton,590502,0.57

In [11]:
df.groupby('candidate').aggregate({'fraction_votes':[min,np.mean,max]})

                fraction_votes
                           min      mean       max
candidate
 No Preference           0.000  0.006484  0.030000
 Uncommitted             0.000  0.000455  0.013000
Ben Carson               0.000  0.058941  0.415000
Bernie Sanders           0.000  0.493316  1.000000
Carly Fiorina            0.000  0.022097  0.117000
Chris Christie           0.002  0.017773  0.087195
Donald Trump             0.000  0.466217  0.915000
Hillary Clinton          0.000  0.461302  1.000000
Jeb Bush                 0.004  0.044524  0.121000
John Kasich              0.000  0.122869  0.639000
Marco Rubio              0.000  0.146959  0.627000
Martin O'Malley          0.000  0.008303  0.132000
Mike Huckabee            0.003  0.024192  0.096000
Rand Paul                0.006  0.034061  0.096000
Rick Santorum            0.000  0.009960  0.073000
Ted Cruz                 0.000  0.243453  1.000000

In [13]:
def fraction_votes_filter(x):
    return x['votes'].sum() > 300000

df.groupby('state').filter(fraction_votes_filter)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078
5,Alabama,AL,Barbour,1005.0,Democrat,Hillary Clinton,2567,0.906
6,Alabama,AL,Bibb,1007.0,Democrat,Bernie Sanders,246,0.197
7,Alabama,AL,Bibb,1007.0,Democrat,Hillary Clinton,942,0.755
8,Alabama,AL,Blount,1009.0,Democrat,Bernie Sanders,395,0.386
9,Alabama,AL,Blount,1009.0,Democrat,Hillary Clinton,564,0.551
10,Alabama,AL,Bullock,1011.0,Democrat,Bernie Sanders,178,0.066
11,Alabama,AL,Bullock,1011.0,Democrat,Hillary Clinton,2451,0.913
12,Alabama,AL,Butler,1013.0,Democrat,Bernie Sanders,156,0.065
13,Alabama,AL,Butler,1013.0,Democrat,Hillary Clinton,2196,0.921
14,Alabama,AL,Calhoun,1015.0,Democrat,Bernie Sanders,1425,0.218
15,Alabama,AL,Calhoun,1015.0,Democrat,Hillary Clinton,5011,0.765
16,Alabama,AL,Chambers,1017.0,Democrat,Bernie Sanders,312,0.095
17,Alabama,AL,Chambers,1017.0,Democrat,Hillary Clinton,2899,0.886
18,Alabama,AL,Cherokee,1019.0,Democrat,Bernie Sanders,268,0.249
19,Alabama,AL,Cherokee,1019.0,Democrat,Hillary Clinton,712,0.661
20,Alabama,AL,Chilton,1021.0,Democrat,Bernie Sanders,289,0.246
21,Alabama,AL,Chilton,1021.0,Democrat,Hillary Clinton,860,0.731
22,Alabama,AL,Choctaw,1023.0,Democrat,Bernie Sanders,273,0.124
23,Alabama,AL,Choctaw,1023.0,Democrat,Hillary Clinton,1772,0.802
24,Alabama,AL,Clarke,1025.0,Democrat,Bernie Sanders,213,0.063
25,Alabama,AL,Clarke,1025.0,Democrat,Hillary Clinton,3148,0.930
26,Alabama,AL,Clay,1027.0,Democrat,Bernie Sanders,135,0.137
27,Alabama,AL,Clay,1027.0,Democrat,Hillary Clinton,807,0.818
28,Alabama,AL,Cleburne,1029.0,Democrat,Bernie Sanders,72,0.238
29,Alabama,AL,Cleburne,1029.0,Democrat,Hillary Clinton,221,0.732
...,...,...,...,...,...,...,...,...
24487,Wisconsin,WI,Vernon,55123.0,Republican,Donald Trump,2437,0.476
24488,Wisconsin,WI,Vernon,55123.0,Republican,John Kasich,635,0.124
24489,Wisconsin,WI,Vernon,55123.0,Republican,Ted Cruz,1878,0.367
24490,Wisconsin,WI,Vilas,55125.0,Republican,Donald Trump,3241,0.521
24491,Wisconsin,WI,Vilas,55125.0,Republican,John Kasich,832,0.134
24492,Wisconsin,WI,Vilas,55125.0,Republican,Ted Cruz,2006,0.322
24493,Wisconsin,WI,Walworth,55127.0,Republican,Donald Trump,7534,0.341
24494,Wisconsin,WI,Walworth,55127.0,Republican,John Kasich,3328,0.151
24495,Wisconsin,WI,Walworth,55127.0,Republican,Ted Cruz,10719,0.485
24496,Wisconsin,WI,Washburn,55129.0,Republican,Donald Trump,1926,0.497
24497,Wisconsin,WI,Washburn,55129.0,Republican,John Kasich,443,0.114
24498,Wisconsin,WI,Washburn,55129.0,Republican,Ted Cruz,1359,0.351
24499,Wisconsin,WI,Washington,55131.0,Republican,Donald Trump,9580,0.235
24500,Wisconsin,WI,Washington,55131.0,Republican,John Kasich,4823,0.118
24501,Wisconsin,WI,Washington,55131.0,Republican,Ted Cruz,25505,0.626
24502,Wisconsin,WI,Waukesha,55133.0,Republican,Donald Trump,27186,0.221
24503,Wisconsin,WI,Waukesha,55133.0,Republican,John Kasich,18521,0.150
24504,Wisconsin,WI,Waukesha,55133.0,Republican,Ted Cruz,75123,0.610
24505,Wisconsin,WI,Waupaca,55135.0,Republican,Donald Trump,4737,0.429
24506,Wisconsin,WI,Waupaca,55135.0,Republican,John Kasich,817,0.074
24507,Wisconsin,WI,Waupaca,55135.0,Republican,Ted Cruz,5194,0.471
24508,Wisconsin,WI,Waushara,55137.0,Republican,Donald Trump,2391,0.451
24509,Wisconsin,WI,Waushara,55137.0,Republican,John Kasich,371,0.070
24510,Wisconsin,WI,Waushara,55137.0,Republican,Ted Cruz,2390,0.451
24511,Wisconsin,WI,Winnebago,55139.0,Republican,Donald Trump,13293,0.388
24512,Wisconsin,WI,Winnebago,55139.0,Republican,John Kasich,3952,0.115
24513,Wisconsin,WI,Winnebago,55139.0,Republican,Ted Cruz,16049,0.469
24514,Wisconsin,WI,Wood,55141.0,Republican,Donald Trump,6941,0.432
24515,Wisconsin,WI,Wood,55141.0,Republican,John Kasich,1479,0.092
24516,Wisconsin,WI,Wood,55141.0,Republican,Ted Cruz,7220,0.450

In [16]:
df[df['state_abbreviation'] == 'AL']['votes'].sum()

1223959

In [17]:
df.groupby(['state_abbreviation','candidate'])['votes'].sum()

state_abbreviation  candidate
AK                  Ben Carson            2401
                    Bernie Sanders         440
                    Donald Trump          7346
                    Hillary Clinton         99
                    John Kasich            892
                    Marco Rubio           3318
                    Ted Cruz              7973
AL                  Ben Carson           87517
                    Bernie Sanders       76399
                    Donald Trump        371735
                    Hillary Clinton     309928
                    John Kasich          37970
                    Marco Rubio         159802
                    Ted Cruz            180608
AR                  Ben Carson           23173
                    Bernie Sanders       64868
                    Donald Trump        133144
                    Hillary Clinton     144580
                    John Kasich          15098
                    Marco Rubio         101235
                    Ted Cruz            123873
AZ                  Bernie Sanders      163400
                    Donald Trump        249916
                    Hillary Clinton     235697
                    John Kasich          53040
                    Ted Cruz            132147
CA                  Bernie Sanders     1502043
                    Donald Trump       1174829
                    Hillary Clinton    1940580
                    John Kasich         176620
                                        ...
VA                  Marco Rubio         327042
                    Ted Cruz            173193
VT                  Ben Carson            2544
                    Bernie Sanders      115863
                    Donald Trump         19968
                    Hillary Clinton      18335
                    John Kasich          18543
                    Marco Rubio          11778
                    Ted Cruz              5929
WA                  Bernie Sanders       19159
                    Donald Trump        403003
                    Hillary Clinton       7140
                    John Kasich          52129
                    Ted Cruz             55719
WI                  Bernie Sanders      567936
                    Donald Trump        386370
                    Hillary Clinton     432767
                    John Kasich         155200
                    Ted Cruz            531129
WV                  Bernie Sanders      123860
                    Donald Trump        156245
                    Hillary Clinton      86354
                    John Kasich          13685
                    Ted Cruz             18208
WY                  Bernie Sanders         156
                    Donald Trump            70
                    Hillary Clinton        124
                    John Kasich              0
                    Marco Rubio            189
                    Ted Cruz               644
Name: votes, Length: 290, dtype: int64

# Operações de merge

In [18]:
from db import DemoDB

In [19]:
database = DemoDB()

Indexing schema. This will take a second...finished!

In [20]:
database.tables

Refreshing schema. Please wait...done!

+--------+---------------+----------------------------------------------------------------------------------+
| Schema | Table         | Columns                                                                          |
+--------+---------------+----------------------------------------------------------------------------------+
| public | Album         | AlbumId, Title, ArtistId                                                         |
| public | Artist        | ArtistId, Name                                                                   |
| public | Customer      | CustomerId, FirstName, LastName, Company, Address, City, State, Country, PostalC |
|        |               | ode, Phone, Fax, Email, SupportRepId                                             |
| public | Employee      | EmployeeId, LastName, FirstName, Title, ReportsTo, BirthDate, HireDate, Address, |
|        |               |  City, State, Country, PostalCode, Phone, Fax, Email                             |
| public | Genre         | GenreId, Name                                                                    |
| public | Invoice       | InvoiceId, CustomerId, InvoiceDate, BillingAddress, BillingCity, BillingState, B |
|        |               | illingCountry, BillingPostalCode, Total                                          |
| public | InvoiceLine   | InvoiceLineId, InvoiceId, TrackId, UnitPrice, Quantity                           |
| public | MediaType     | MediaTypeId, Name                                                                |
| public | Playlist      | PlaylistId, Name                                                                 |
| public | PlaylistTrack | PlaylistId, TrackId                                                              |
| public | Track         | TrackId, Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, Uni |
|        |               | tPrice                                                                           |
+--------+---------------+----------------------------------------------------------------------------------+

In [21]:
album = database.tables.Album.all()

In [22]:
album.head()

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

In [23]:
artist = database.tables.Artist.all()

In [24]:
artist.head()

   ArtistId               Name
0         1              AC/DC
1         2             Accept
2         3          Aerosmith
3         4  Alanis Morissette
4         5    Alice In Chains

In [25]:
album_artist = pd.merge(artist,album)

In [26]:
album_artist.head()

   ArtistId       Name  AlbumId                                  Title
0         1      AC/DC        1  For Those About To Rock We Salute You
1         1      AC/DC        4                      Let There Be Rock
2         2     Accept        2                      Balls to the Wall
3         2     Accept        3                      Restless and Wild
4         3  Aerosmith        5                               Big Ones

In [27]:
album_artist = pd.merge(artist,album,on='ArtistId')

In [28]:
album_artist.head()

   ArtistId       Name  AlbumId                                  Title
0         1      AC/DC        1  For Those About To Rock We Salute You
1         1      AC/DC        4                      Let There Be Rock
2         2     Accept        2                      Balls to the Wall
3         2     Accept        3                      Restless and Wild
4         3  Aerosmith        5                               Big Ones

In [29]:
album.rename(columns={'ArtistId':'Artist_ID'})

     AlbumId                                              Title  Artist_ID
0          1              For Those About To Rock We Salute You          1
1          2                                  Balls to the Wall          2
2          3                                  Restless and Wild          2
3          4                                  Let There Be Rock          1
4          5                                           Big Ones          3
5          6                                 Jagged Little Pill          4
6          7                                           Facelift          5
7          8                                     Warner 25 Anos          6
8          9                     Plays Metallica By Four Cellos          7
9         10                                         Audioslave          8
10        11                                       Out Of Exile          8
11        12                                BackBeat Soundtrack          9
12        13                           The Best Of Billy Cobham         10
13        14           Alcohol Fueled Brewtality Live! [Disc 1]         11
14        15           Alcohol Fueled Brewtality Live! [Disc 2]         11
15        16                                      Black Sabbath         12
16        17                    Black Sabbath Vol. 4 (Remaster)         12
17        18                                         Body Count         13
18        19                                   Chemical Wedding         14
19        20   The Best Of Buddy Guy - The Millenium Collection         15
20        21                                       Prenda Minha         16
21        22                              Sozinho Remix Ao Vivo         16
22        23                                     Minha Historia         17
23        24                                     Afrociberdelia         18
24        25                                    Da Lama Ao Caos         18
25        26                                Acústico MTV [Live]         19
26        27                                Cidade Negra - Hits         19
27        28                                           Na Pista         20
28        29                                     Axé Bahia 2001         21
29        30                       BBC Sessions [Disc 1] [Live]         22
..       ...                                                ...        ...
317      318                           SCRIABIN: Vers la flamme        250
318      319  Armada: Music from the Courts of England and S...        251
319      320                    Mozart: Symphonies Nos. 40 & 41        248
320      321                                      Back to Black        252
321      322                                              Frank        252
322      323              Carried to Dust (Bonus Track Version)        253
323      324          Beethoven: Symphony No. 6 'Pastoral' Etc.        254
324      325                   Bartok: Violin & Viola Concertos        255
325      326             Mendelssohn: A Midsummer Night's Dream        256
326      327                 Bach: Orchestral Suites Nos. 1 - 4        257
327      328      Charpentier: Divertissements, Airs & Concerts        258
328      329                             South American Getaway        259
329      330                            Górecki: Symphony No. 3        260
330      331                           Purcell: The Fairy Queen        261
331      332                      The Ultimate Relexation Album        262
332      333                  Purcell: Music for the Queen Mary        263
333      334                       Weill: The Seven Deadly Sins        264
334      335  J.S. Bach: Chaconne, Suite in E Minor, Partita...        265
335      336  Prokofiev: Symphony No.5 & Stravinksy: Le Sacr...        248
336      337                   Szymanowski: Piano Works, Vol. 1        266
337      338                        Nielsen: The Six Symphonies        267
338      339  Great Recordings of the Century: Paganini's 24...        268
339      340        Liszt - 12 Études D'Execution Transcendante        269
340      341  Great Recordings of the Century - Shubert: Sch...        270
341      342  Locatelli: Concertos for Violin, Strings and C...        271
342      343                             Respighi:Pines of Rome        226
343      344  Schubert: The Late String Quartets & String Qu...        272
344      345                                Monteverdi: L'Orfeo        273
345      346                              Mozart: Chamber Music        274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...        275

[347 rows x 3 columns]

In [37]:
album.drop('AlbumId',axis=1)

                                                 Title  ArtistId
0                For Those About To Rock We Salute You         1
1                                    Balls to the Wall         2
2                                    Restless and Wild         2
3                                    Let There Be Rock         1
4                                             Big Ones         3
5                                   Jagged Little Pill         4
6                                             Facelift         5
7                                       Warner 25 Anos         6
8                       Plays Metallica By Four Cellos         7
9                                           Audioslave         8
10                                        Out Of Exile         8
11                                 BackBeat Soundtrack         9
12                            The Best Of Billy Cobham        10
13            Alcohol Fueled Brewtality Live! [Disc 1]        11
14            Alcohol Fueled Brewtality Live! [Disc 2]        11
15                                       Black Sabbath        12
16                     Black Sabbath Vol. 4 (Remaster)        12
17                                          Body Count        13
18                                    Chemical Wedding        14
19    The Best Of Buddy Guy - The Millenium Collection        15
20                                        Prenda Minha        16
21                               Sozinho Remix Ao Vivo        16
22                                      Minha Historia        17
23                                      Afrociberdelia        18
24                                     Da Lama Ao Caos        18
25                                 Acústico MTV [Live]        19
26                                 Cidade Negra - Hits        19
27                                            Na Pista        20
28                                      Axé Bahia 2001        21
29                        BBC Sessions [Disc 1] [Live]        22
..                                                 ...       ...
317                           SCRIABIN: Vers la flamme       250
318  Armada: Music from the Courts of England and S...       251
319                    Mozart: Symphonies Nos. 40 & 41       248
320                                      Back to Black       252
321                                              Frank       252
322              Carried to Dust (Bonus Track Version)       253
323          Beethoven: Symphony No. 6 'Pastoral' Etc.       254
324                   Bartok: Violin & Viola Concertos       255
325             Mendelssohn: A Midsummer Night's Dream       256
326                 Bach: Orchestral Suites Nos. 1 - 4       257
327      Charpentier: Divertissements, Airs & Concerts       258
328                             South American Getaway       259
329                            Górecki: Symphony No. 3       260
330                           Purcell: The Fairy Queen       261
331                      The Ultimate Relexation Album       262
332                  Purcell: Music for the Queen Mary       263
333                       Weill: The Seven Deadly Sins       264
334  J.S. Bach: Chaconne, Suite in E Minor, Partita...       265
335  Prokofiev: Symphony No.5 & Stravinksy: Le Sacr...       248
336                   Szymanowski: Piano Works, Vol. 1       266
337                        Nielsen: The Six Symphonies       267
338  Great Recordings of the Century: Paganini's 24...       268
339        Liszt - 12 Études D'Execution Transcendante       269
340  Great Recordings of the Century - Shubert: Sch...       270
341  Locatelli: Concertos for Violin, Strings and C...       271
342                             Respighi:Pines of Rome       226
343  Schubert: The Late String Quartets & String Qu...       272
344                                Monteverdi: L'Orfeo       273
345                              Mozart: Chamber Music       274
346  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 2 columns]